#%RAML 1.0 NamedExample
qbotica-po-sapi-example:
  {
  "K430": [
    {
      "customerNo": "K430",
      "CUSTOMERPONO": "30110532_376",
      "ECTPONUMBER": "",
      "EXPECTEDSHIPDATE": "",
      "DockDate": "2024-09-19",
      "OrderDate": "02/02/2023",
      "SHIPTONAME": "TRANE TECHNOLOGIES CO LLC",
      "SHIPTOADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
      "POLINENO": "18.6",
      "QUANTITYORDERED": "16",
      "UNITPRICE": "0.00",
      "CUSTOMERPARTNO": "SXA029C2BPA",
      "COPELANDMODELNO": "ZP29K5E-PFJ-303",
      "ITEMDESCRIPTION": "",
      "REJECTEDMESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
    },
    {
      "customerNo": "K430",
      "CUSTOMERPONO": "30110532_376",
      "ECTPONUMBER": "",
      "EXPECTEDSHIPDATE": "",
      "DockDate": "2024-09-19",
      "OrderDate": "02/02/2023",
      "SHIPTONAME": "TRANE TECHNOLOGIES CO LLC",
      "SHIPTOADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
      "POLINENO": "73.9",
      "QUANTITYORDERED": "16",
      "UNITPRICE": "0.00",
      "CUSTOMERPARTNO": "X24021812030",
      "COPELANDMODELNO": "ZP54K3E-TFD-230",
      "ITEMDESCRIPTION": "",
      "REJECTEDMESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
    },
    {
      "customerNo": "K430",
      "CUSTOMERPONO": "30110532_376",
      "ECTPONUMBER": "",
      "EXPECTEDSHIPDATE": "",
      "DockDate": "2024-09-19",
      "OrderDate": "02/02/2023",
      "SHIPTONAME": "TRANE TECHNOLOGIES CO LLC",
      "SHIPTOADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
      "POLINENO": "28.7",
      "QUANTITYORDERED": "16",
      "UNITPRICE": "0.00",
      "CUSTOMERPARTNO": "SXA034B4BPA",
      "COPELANDMODELNO": "ZP34K5E-TFD-303",
      "ITEMDESCRIPTION": "",
      "REJECTEDMESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
    },
    {
      "customerNo": "K430",
      "CUSTOMERPONO": "30110532_376",
      "ECTPONUMBER": "",
      "EXPECTEDSHIPDATE": "",
      "DockDate": "2024-09-19",
      "OrderDate": "02/02/2023",
      "SHIPTONAME": "TRANE TECHNOLOGIES CO LLC",
      "SHIPTOADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
      "POLINENO": "45.3",
      "QUANTITYORDERED": "16",
      "UNITPRICE": "0.00",
      "CUSTOMERPARTNO": "SXA054B3BPA",
      "COPELANDMODELNO": "ZP54K5E-TF5-303",
      "ITEMDESCRIPTION": "",
      "REJECTEDMESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
    },
    {
      "customerNo": "K430",
      "CUSTOMERPONO": "30110532_376",
      "ECTPONUMBER": "",
      "EXPECTEDSHIPDATE": "",
      "DockDate": "2024-09-19",
      "OrderDate": "02/02/2023",
      "SHIPTONAME": "TRANE TECHNOLOGIES CO LLC",
      "SHIPTOADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
      "POLINENO": "29.2",
      "QUANTITYORDERED": "16",
      "UNITPRICE": "0.00",
      "CUSTOMERPARTNO": "SXA036B1BPA",
      "COPELANDMODELNO": "ZP36K5E-PFV-303",
      "ITEMDESCRIPTION": "",
      "REJECTEDMESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
    },
    {
      "customerNo": "K430",
      "CUSTOMERPONO": "30110532_376",
      "ECTPONUMBER": "",
      "EXPECTEDSHIPDATE": "",
      "DockDate": "2024-09-19",
      "OrderDate": "02/02/2023",
      "SHIPTONAME": "TRANE TECHNOLOGIES CO LLC",
      "SHIPTOADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
      "POLINENO": "17.5",
      "QUANTITYORDERED": "16",
      "UNITPRICE": "0.00",
      "CUSTOMERPARTNO": "SXA029C1BPA",
      "COPELANDMODELNO": "ZP29K5E-PFV-303",
      "ITEMDESCRIPTION": "",
      "REJECTEDMESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
    },
    {
      "customerNo": "K430",
      "CUSTOMERPONO": "30110532_376",
      "ECTPONUMBER": "",
      "EXPECTEDSHIPDATE": "",
      "DockDate": "2024-09-19",
      "OrderDate": "02/02/2023",
      "SHIPTONAME": "TRANE TECHNOLOGIES CO LLC",
      "SHIPTOADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
      "POLINENO": "35.8",
      "QUANTITYORDERED": "16",
      "UNITPRICE": "0.00",
      "CUSTOMERPARTNO": "SXA039B4BPA",
      "COPELANDMODELNO": "ZP39K5E-TFD-303",
      "ITEMDESCRIPTION": "",
      "REJECTEDMESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
    },
    {
      "customerNo": "K430",
      "CUSTOMERPONO": "30110532_376",
      "ECTPONUMBER": "",
      "EXPECTEDSHIPDATE": "",
      "DockDate": "2024-09-19",
      "OrderDate": "02/02/2023",
      "SHIPTONAME": "TRANE TECHNOLOGIES CO LLC",
      "SHIPTOADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
      "POLINENO": "2.4",
      "QUANTITYORDERED": "16",
      "UNITPRICE": "0.00",
      "CUSTOMERPARTNO": "SXA020C2BPA",
      "COPELANDMODELNO": "ZP20K5E-PFJ-303",
      "ITEMDESCRIPTION": "",
      "REJECTEDMESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
    },
    {
      "customerNo": "K430",
      "CUSTOMERPONO": "30110532_376",
      "ECTPONUMBER": "",
      "EXPECTEDSHIPDATE": "",
      "DockDate": "2024-09-19",
      "OrderDate": "02/02/2023",
      "SHIPTONAME": "TRANE TECHNOLOGIES CO LLC",
      "SHIPTOADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
      "POLINENO": "42.1",
      "QUANTITYORDERED": "16",
      "UNITPRICE": "0.00",
      "CUSTOMERPARTNO": "SXA051B4BPA",
      "COPELANDMODELNO": "ZP51K5E-TFD-303",
      "ITEMDESCRIPTION": "",
      "REJECTEDMESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
    },
    {
      "customerNo": "K430",
      "CUSTOMERPONO": "30110532_376",
      "ECTPONUMBER": "",
      "EXPECTEDSHIPDATE": "",
      "DockDate": "2024-09-19",
      "OrderDate": "02/02/2023",
      "SHIPTONAME": "TRANE TECHNOLOGIES CO LLC",
      "SHIPTOADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
      "POLINENO": "31.11",
      "QUANTITYORDERED": "16",
      "UNITPRICE": "0.00",
      "CUSTOMERPARTNO": "SXA036B4BPA",
      "COPELANDMODELNO": "ZP36K5E-TFD-303",
      "ITEMDESCRIPTION": "",
      "REJECTEDMESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
    },
    {
      "customerNo": "K430",
      "CUSTOMERPONO": "30110532_376",
      "ECTPONUMBER": "",
      "EXPECTEDSHIPDATE": "",
      "DockDate": "2024-09-19",
      "OrderDate": "02/02/2023",
      "SHIPTONAME": "TRANE TECHNOLOGIES CO LLC",
      "SHIPTOADDRESS": "TRANE WACO 182 COTTON BELT PKWY  MCGREGOR TX",
      "POLINENO": "7.10",
      "QUANTITYORDERED": "16",
      "UNITPRICE": "0.00",
      "CUSTOMERPARTNO": "SXA021C3BPA",
      "COPELANDMODELNO": "ZP21K5E-TF5-303",
      "ITEMDESCRIPTION": "",
      "REJECTEDMESSAGE": "DUPLICATE ORDER FOR ITEM/REQ DATE PO#"
    }
  ]
}